name: First workflow
on: workflow_dispatch
jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Print greating
        run: |
          echo "Hello"
          echo "ca va ?"
      - name: Pint goodbye
        run: echo "Bye"
