name: Test reusable
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: simple text
                required: false
                default: hello
                type: string
        outputs:
            result:
                description: result of workflow
                value: ${{ jobs.deploy-test.outputs.result }}
jobs:
    deploy-test:
        runs-on: ubuntu-latest
        outputs:
            result: ${{ steps.output-result.outputs.result }}
        steps:
            - name: Output information
              id: output-info
              run: echo  ${{ inputs.artifact-name }}
            - name: result
              id: output-result
              run: echo "result=success" >> $GITHUB_OUTPUT \;
          