name: Test reusable
on: workflow_call:
    inputs:
        artifact-name:
            description: simple text
            required: false
            default: hello
            type: string
jobs:
    deploy-test:
        runs-on: ubuntu-latest
        steps:
            - name: Output information
              run: echo  ${{ inputs.artifact-name }}