name: Test project
on:
    workflow_dispatch:
    push:
        branches: 
            - main
        paths-ignore:
            - "docs/**"
            - "README.md"
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main
            - "dev-*"
            - "feat/**"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Out github
              run: echo "${{ toJSON(github)}}"
            - name: get code
              uses: actions/checkout@v6
            - name: Install NodeJS
              uses: actions/setup-node@v3              
              with:
                node-version: 18
            - name: Cache dependencies
              uses: actions/cache@v5
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    build:
        runs-on: ubuntu-latest
        needs: test
        continue-on-error: true
        strategy:
          matrix:
            node-version: [14,16, 18]
        outputs:
          script-files: ${{ steps.publish-script-file.outputs.script-file}}
        steps:
          - name: get code
            uses: actions/checkout@v6
          - name: Install NodeJS
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
          - name: Cache dependencies
            uses: actions/cache@v5
            with:
              path: ~/.npm
              key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          - name: install dependencies
            run: npm ci
          - name: build wbsite
            run: npm run build
          - name: publish js file
            id: publish-script-file
            run: find dist/assets/*.js -type f -execdir echo "script-file={}" >> $GITHUB_OUTPUT \;
          - name: Upload artifacts
            uses: actions/upload-artifact@v7
            with:
              name: dist-files
              path: dist

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: list output de build
            run: echo ${{ needs.build.outputs.script-files }}
          - name: get build artifacts
            uses: actions/download-artifact@v8
            with:
              name: dist-files
          - name: output content
            run: ls
          - name: Deploy
            run: echo "Deploying project"